version: '3.7'

services:
  web:
    image: flask-secret-app:latest
    build: .
    ports:
      - "5000:5000"
    secrets:
      - SECRET_KEY
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  SECRET_KEY:
    file: ./flag.txt