version: '3.8'

services:
  web:
    build: .
    ports:
      - "6969:6969"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=JJHFJGDXUFJHZXFJHSDGDBFIS
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
      - FLAG=MED{hehehehehehe}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgrASDFAes
      - POSTGRES_PASSWORD=DFASDFAF
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: